#!/usr/bin/env bash
set -euo pipefail

PACKAGE_DIR=""

usage() {
  cat >&2 <<'EOF'
usage: scripts/smoke_release.sh [--package-dir <dist-package>]

Runs an offline smoke test against fastk_bridge and fastk_admin from a release
package generated by scripts/build_release.sh.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --package-dir)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --package-dir" >&2
        exit 2
      fi
      PACKAGE_DIR="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

if [ -z "$PACKAGE_DIR" ]; then
  VERSION="$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -n 1)"
  HOST_TARGET="$(rustc -vV | awk '/^host:/{print $2}')"
  CANDIDATE="$REPO_ROOT/dist/fastk-$VERSION-$HOST_TARGET"
  if [ -d "$CANDIDATE" ]; then
    PACKAGE_DIR="$CANDIDATE"
  else
    PACKAGE_DIR="$(find "$REPO_ROOT/dist" -maxdepth 1 -type d -name "fastk-$VERSION-*" 2>/dev/null | sort | tail -n 1 || true)"
    if [ -z "$PACKAGE_DIR" ]; then
      echo "release package not found under dist; run scripts/build_release.sh first" >&2
      exit 1
    fi
  fi
fi

BRIDGE="$PACKAGE_DIR/bin/fastk_bridge"
ADMIN="$PACKAGE_DIR/bin/fastk_admin"
if [ ! -x "$BRIDGE" ]; then
  if [ -x "$PACKAGE_DIR/bin/fastk_bridge.exe" ]; then
    BRIDGE="$PACKAGE_DIR/bin/fastk_bridge.exe"
  else
    echo "missing executable fastk_bridge in release package: $PACKAGE_DIR" >&2
    exit 1
  fi
fi
if [ ! -x "$ADMIN" ]; then
  if [ -x "$PACKAGE_DIR/bin/fastk_admin.exe" ]; then
    ADMIN="$PACKAGE_DIR/bin/fastk_admin.exe"
  else
    echo "missing executable fastk_admin in release package: $PACKAGE_DIR" >&2
    exit 1
  fi
fi

STORE="$REPO_ROOT/target/release-smoke-store"
INPUTS="$REPO_ROOT/target/release-smoke-input"
rm -rf "$STORE" "$INPUTS"
mkdir -p "$STORE" "$INPUTS"

"$BRIDGE" --help >/dev/null 2>&1
"$ADMIN" validate --root "$STORE" --verbose >/dev/null

cat > "$INPUTS/kline.json" <<'JSON'
{
  "timeframe_ms": 60000,
  "price_scale": 100000,
  "volume_scale": 100000,
  "records": [
    { "ts": 1706745600000, "open": 10000000, "high": 10020000, "low": 9980000, "close": 10010000, "volume": 10000 },
    { "ts": 1706745660000, "open": 10010000, "high": 10030000, "low": 10000000, "close": 10020000, "volume": 10020 },
    { "ts": 1706745720000, "open": 10020000, "high": 10040000, "low": 10010000, "close": 10030000, "volume": 10030 }
  ]
}
JSON

"$BRIDGE" write-kline-range \
  --root "$STORE" \
  --symbol BTCUSDT \
  --timeframe 1m \
  --input-json "$INPUTS/kline.json" > "$INPUTS/write_kline.out"
grep -q '"written_record_count": 3' "$INPUTS/write_kline.out"

"$BRIDGE" read-kline-range \
  --root "$STORE" \
  --symbol BTCUSDT \
  --timeframe 1m \
  --start-ts 1706745600000 \
  --end-ts 1706745720000 > "$INPUTS/read_kline.out"
grep -q '"records": \[' "$INPUTS/read_kline.out"
grep -q '"close": 10030000' "$INPUTS/read_kline.out"

cat > "$INPUTS/scalar.json" <<'JSON'
{
  "timeframe_ms": 60000,
  "records": [
    { "ts": 1706745600000, "value": 42 },
    { "ts": 1706745660000, "value": 43 },
    { "ts": 1706745720000, "value": 44 }
  ]
}
JSON

"$BRIDGE" write-scalar-range \
  --root "$STORE" \
  --symbol BTCUSDT \
  --timeframe 1m \
  --category feature \
  --name rsi_14 \
  --input-json "$INPUTS/scalar.json" > "$INPUTS/write_scalar.out"
grep -q '"written_record_count": 3' "$INPUTS/write_scalar.out"

"$BRIDGE" read-scalar-range \
  --root "$STORE" \
  --symbol BTCUSDT \
  --timeframe 1m \
  --category feature \
  --name rsi_14 \
  --start-ts 1706745600000 \
  --end-ts 1706745720000 > "$INPUTS/read_scalar.out"
grep -q '"value": 44' "$INPUTS/read_scalar.out"

"$BRIDGE" query-scalar-predicate \
  --root "$STORE" \
  --symbol BTCUSDT \
  --timeframe 1m \
  --category feature \
  --name rsi_14 \
  --start-ts 1706745600000 \
  --end-ts 1706745720000 \
  --predicate gt \
  --value 42 \
  --return-values > "$INPUTS/query_scalar_predicate.out"
grep -q '"rows_matched": 2' "$INPUTS/query_scalar_predicate.out"
grep -q '"value": 44' "$INPUTS/query_scalar_predicate.out"

"$ADMIN" validate --root "$STORE" --verbose >/dev/null
"$ADMIN" scrub --root "$STORE" --verbose --dry-run >/dev/null

echo "smoke passed"
